Models/Photo.cs
using JSON_DAL;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.Design;
using System.Linq;
using System.Reflection;
using System.Web;

namespace PhotosManager.Models
{
    public class Photo
    {
        const string PhotosFolder = @"/App_Assets/Photos/";
        const string DefaultPhoto = @"No_Image.png";

        public int Id { get; set; }
        public int OwnerId { get; set; }            // Id du propriétaire de la photo
        [Display(Name = "Titre"), Required(ErrorMessage = "Obligatoire")]
        public string Title { get; set; }           // Titre de la photo
        [Display(Name = "Description"), Required(ErrorMessage = "Obligatoire")]
        public string Description { get; set; }     // Description de la photo
        public DateTime CreationDate { get; set; }  // Date de création
        public bool Shared { get; set; }            // Indicateur de partage ("true" ou "false")

        [JsonIgnore]
        private int _likesCount = -1;
        [JsonIgnore]
        private List<Like> _likesList = null;
        [JsonIgnore]
        private int _commentsCount = -1;
        [JsonIgnore]
        private List<Comment> _commentsList = null;
        public void ResetCountsCalc()
        {
            _likesCount = -1;
            _likesList = null;
            _commentsCount = -1;
            _commentsList = null;
        }
        [JsonIgnore]
        public int LikesCount
        {
            get
            {
                if (_likesCount == -1)
                    _likesCount = Likes.Count();
                return _likesCount;
            }
        }
        [JsonIgnore]
        public List<Like> Likes
        {
            get
            {
                if (_likesList == null)
                    _likesList = DB.Likes.ToList().Where(l => l.PhotoId == Id && l.CommentId == 0).ToList();
                return _likesList;
            }
        }

        [JsonIgnore]
        public string UsersLikesList
        {
            get
            {
                string UsersLikesList = "";
                foreach (var like in Likes)
                {
                    UsersLikesList += DB.Users.Get(like.UserId).Name + "\n";
                }
                return UsersLikesList;
            }
        }
        [JsonIgnore]
        public string UsersCommentList
        {
            get
            {
                string UsersCommentList = "";
                foreach (var comment in Comments.DistinctBy(c=>c.OwnerId))
                {
                    User owner = comment.Owner;
                    if (owner != null)
                        UsersCommentList += owner.Name + "\n";
                }
                return UsersCommentList;
            }
        }
        [ImageAsset(PhotosFolder, DefaultPhoto)]
        public string Image { get; set; }           // Url relatif de l'image

        public Photo()
        {
            Id = 0;
            CreationDate = DateTime.Now;
            Shared = false;
            Image = PhotosFolder + DefaultPhoto;
        }
        [JsonIgnore]
        public User Owner => DB.Users.Get(OwnerId);
        [JsonIgnore]
        public int CommentsCount
        {
            get
            {
                if (_commentsCount == -1)
                    _commentsCount = Comments.Count();
                return _commentsCount;
            }
        }
        [JsonIgnore]
        public List<Comment> Comments
        {
            get
            {
                if (_commentsList == null)
                    _commentsList = DB.Comments.ToList().Where(c => c.PhotoId == Id && c.ParentId == 0).ToList();
                return _commentsList;
            }
        }
    }
}

Controllers/PhotosController.cs
using PhotosManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Tokenizer.Symbols;
using static PhotosManager.Controllers.AccessControl;

namespace PhotosManager.Controllers
{
    [UserAccess]
    public class PhotosController : Controller
    {
        const string IllegalAccessUrl = "/Accounts/Login?message=Tentative d'accès illégal!&success=false";
        private const string SortAscKey = "PhotosSortAsc";
        private const string SortTypeKey = "PhotosSortType";
        public ActionResult ToggleSortDirection()
        {
            bool current = Session[SortAscKey] != null && (bool)Session[SortAscKey];
            Session[SortAscKey] = !current;

            string sortType = Session[SortTypeKey]?.ToString() ?? "date";
            return RedirectToAction("List", new { sortType = sortType });
        }
        public ActionResult ToggleSearch()
        {
            Session["ShowSearch"] = !(bool)Session["ShowSearch"];
            return RedirectToAction("List");
        }

        public ActionResult SetSearchKeywords(string keywords)
        {
            Session["SetSearchKeywords"] = keywords;
            return RedirectToAction("List");
        }

        public ActionResult SetPhotoOwnerSearchId(int id)
        {
            Session["SetPhotoOwnerSearchId"] = id;
            return RedirectToAction("List");
        }


        public ActionResult GetPhotos(bool forceRefresh = false)
        {
            if (forceRefresh || DB.Photos.HasChanged || DB.Likes.HasChanged || DB.Users.HasChanged || DB.Comments.HasChanged)
            {
                if (DB.Likes.HasChanged || DB.Comments.HasChanged)
                    DB.Photos.ResetLikesCount();

                List<Photo> photos = DB.Photos.ToList();
                User connectedUser = (User)Session["ConnectedUser"];
                string sortType = Session["PhotosSortType"]?.ToString() ?? "date";
                bool asc = Session["PhotosSortAsc"] != null && (bool)Session["PhotosSortAsc"];
                int selectedUser = Session["SetPhotoOwnerSearchId"] != null ? (int)Session["SetPhotoOwnerSearchId"] : 0;
                string keyword = Session["SetSearchKeywords"] != null ? Session["SetSearchKeywords"].ToString() : string.Empty;



                switch (sortType)
                {
                    case "likes":
                        photos = asc
                            ? photos.OrderBy(p => p.Likes.Count).ToList()
                            : photos.OrderByDescending(p => p.Likes.Count).ToList();
                        break;

                    case "comments":
                        photos = asc
                            ? photos.OrderBy(p => p.Comments.Count).ToList()
                            : photos.OrderByDescending(p => p.Comments.Count).ToList();
                        break;

                    case "owner":
                        if (connectedUser != null)
                        {
                            var ownerPhotos = photos.Where(p => p.OwnerId == connectedUser.Id);
                            photos = asc
                                ? ownerPhotos.OrderBy(p => p.CreationDate).ToList()
                                : ownerPhotos.OrderByDescending(p => p.CreationDate).ToList();
                        }
                        break;

                    case "ownerLikes":
                        if (connectedUser != null)
                        {
                            var liked = photos.Where(p => p.Likes.Any(l => l.UserId == connectedUser.Id));
                            photos = asc
                                ? liked.OrderBy(p => p.CreationDate).ToList()
                                : liked.OrderByDescending(p => p.CreationDate).ToList();
                        }
                        break;

                    case "ownerDontLike":
                        if (connectedUser != null)
                        {
                            var unliked = photos.Where(p => !p.Likes.Any(l => l.UserId == connectedUser.Id));
                            photos = asc
                                ? unliked.OrderBy(p => p.CreationDate).ToList()
                                : unliked.OrderByDescending(p => p.CreationDate).ToList();
                        }
                        break;

                    case "ownerComments":
                        if (connectedUser != null)
                        {
                            var commented = photos.Where(p => p.Comments.Any(c => c.OwnerId == connectedUser.Id));
                            photos = asc
                                ? commented.OrderBy(p => p.CreationDate).ToList()
                                : commented.OrderByDescending(p => p.CreationDate).ToList();
                        }
                        break;

                    case "ownerNoComment":
                        if (connectedUser != null)
                        {
                            var uncommented = photos.Where(p => !p.Comments.Any(c => c.OwnerId == connectedUser.Id));
                            photos = asc
                                ? uncommented.OrderBy(p => p.CreationDate).ToList()
                                : uncommented.OrderByDescending(p => p.CreationDate).ToList();
                        }
                        break;

                    case "date":
                    default:
                        photos = asc
                            ? photos.OrderBy(p => p.CreationDate).ToList()
                            : photos.OrderByDescending(p => p.CreationDate).ToList();
                        break;
                }

                if (Session["ShowSearch"] != null && (bool)Session["ShowSearch"])
                {
                    if (!string.IsNullOrEmpty(keyword))
                    {
                        keyword = keyword.ToLower();
                        photos = photos.Where(p => p.Title.ToLower().Contains(keyword) || p.Description.ToLower().Contains(keyword)).ToList();
                    }

                    if (selectedUser > 0)
                    {
                        photos = photos.Where(p => p.OwnerId == selectedUser).ToList();
                    }
                }


                return PartialView(photos);
            }

            return null;
        }


        public ActionResult List(string sortType = "date")
        {
            Session["id"] = null;
            Session["IsOwner"] = null;

            if (!string.IsNullOrEmpty(sortType))
            {
                Session["PhotosSortType"] = sortType;
            }

            DB.Photos.ResetLikesCount();

            var users = DB.Users
                .ToList()
                .Select(u => new
                {
                    u.Id,
                    Name = u.Name,
                    PhotoCount = DB.Photos.ToList().Count(p => p.OwnerId == u.Id)
                })
                .Where(u => u.PhotoCount > 0)
                .OrderBy(u => u.Name)
                .ToList();

            ViewBag.UsersWithPhotos = users;

            return View();
        }
        public ActionResult Create()
        {
            return View(new Photo());
        }
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Photo photo)
        {
            photo.OwnerId = ((User)Session["ConnectedUser"]).Id;
            photo.CreationDate = DateTime.Now;
            DB.Photos.Add(photo);
            return RedirectToAction("List");
        }
        public ActionResult Edit()
        {
            if (Session["id"] != null && Session["IsOwner"] != null && (bool)Session["IsOwner"])
            {
                int id = (int)Session["id"];
                Photo photo = DB.Photos.Get(id);
                User connectedUser = (User)Session["ConnectedUser"];
                if (photo != null)
                {
                    if (connectedUser.IsAdmin || photo.OwnerId == connectedUser.Id)
                    {
                        return View(photo);
                    }
                    return Redirect(IllegalAccessUrl);
                }
            }
            return Redirect(IllegalAccessUrl);
        }
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(Photo photo)
        {
            User connectedUser = ((User)Session["ConnectedUser"]);
            if (Session["IsOwner"] != null? (bool)Session["IsOwner"] : false)
            {
                Photo storedPhoto = DB.Photos.Get((int)Session["id"]);
                photo.Id = storedPhoto.Id;
                photo.OwnerId = storedPhoto.OwnerId;
                photo.CreationDate = storedPhoto.CreationDate;
                DB.Photos.Update(photo);
                return RedirectToAction("List");
            }
            return Redirect(IllegalAccessUrl);
        }
        public ActionResult GetDetails(bool forceRefresh = false)
        {
            if (forceRefresh || DB.Photos.HasChanged || DB.Users.HasChanged || DB.Comments.HasChanged || DB.Likes.HasChanged)
            {
                int photoId = Session["currentPhotoId"] != null ? (int)Session["currentPhotoId"] : 0;
                DB.Photos.ResetLikesCount();
                Photo photo = DB.Photos.Get(photoId);
                if (photo != null)
                    return PartialView(photo);
            }
            return null;
        }
        public ActionResult Details(int id)
        {
            Photo photo = DB.Photos.Get(id);
            if (photo != null)
            {
                Session["currentPhotoId"] = id;
                User connectedUser = ((User)Session["ConnectedUser"]);
                Session["IsOwner"] = connectedUser.IsAdmin || photo.OwnerId == connectedUser.Id;
                if ((bool)Session["IsOwner"] || photo.Shared)
                    return View();
                else

Views/Photos/Create.cshtml
@{
    ViewBag.Title = "Nouvelle photo";
    Html.RenderPartial("PhotoForm");
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photos/Details.cshtml
@{
    ViewBag.Title = "Détails de photo";
    int currentPhotoId = (int)Session["currentPhotoId"];
    var user = ((PhotosManager.Models.User)Session["ConnectedUser"]);
}
<div id="DetailsPanel"> <!-- Auto refreshed --></div>
<hr />
<!-- Create new comment command icon -->
<div class="commentFooter ">
    <h4 style="margin-left:22px;">Commentaires</h4>
    <div class="commentSubFooter" style="font-size:1em">
        <i class="newCommentCmd cmdIcon fa-regular fa-comment" style="margin-top:-3px; z-index:1;font-size:1.5em" parentId="0" title="Ajouter un commentaire"></i>
    </div>
</div>

<details open style="position:relative; top:-40px;" id="commentDetails">
    <summary style="border: none; background: none; "></summary>

    <!-- All comments rendering -->
    <div class="commentsSection" id="commentsSection"> <!-- auto refreshed --> </div>

    <!-- Hidden programmatically new comment UI -->
    <div class="newCommentLayout" photoId="@currentPhotoId" createCommentparentId="0">
        <div class="UserSmallAvatar" style="background-image:url('@user.Avatar')" title="@user.Name"></div>
        <textarea class="form-control" rows="1" placeholder="commenter"></textarea>
        <div><!--spacer--></div>
        <div class="editCommentFooter">
            <div><!--spacer--></div>
            <!-- Commit create command icon -->
            <span class="createCommentCmd cmdIconSmall fa fa-check" parentId="0"></span>
            <!-- Abort update command icon -->
            <span class="abortCreateCommentCmd cmdIconSmall fa fa-times" parentId="0"></span>
        </div>
    </div>
</details>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        let commentsSection;
        let scrollAnimationSpeed = 1000;
        $(() => {
            detailsPanel = new AutoRefreshedPanel("DetailsPanel", "/Photos/GetDetails", GPRR, detailsPanelAttachEvents);
            commentsSection = new AutoRefreshedPanel("commentsSection", "/Photos/GetComments", GPRR, commentsSectionAttachEvents);
        })
        function detailsPanelAttachEvents() {
            $("#addRemoveLikeCmd").off();
            $("#addRemoveLikeCmd").click(function (e) {
                detailsPanel.command("/Photos/TogglePhotoLike/" + $(this).attr("photoId"));
                e.preventDefault();
            });
        }
        function commentsSectionAttachEvents() {
            $("#commentDetails .fa-thumbs-up").off();
            $("#commentDetails .fa-thumbs-up").click(function (e) {
                commentsSection.command("/Photos/ToggleCommentLike/" + $(this).attr("commentId"));
                e.preventDefault();
            });
            $(".editCommentLayout").hide();
            $(".newCommentLayout").hide();
            $(".responseLayout").hide();

            $(".newCommentCmd").off();
            $(".newCommentCmd").click(function () {
                $("#commentDetails").prop('open', true);

                commentsSection.pause();
                let parentId = $(this).attr("parentId");
                $(`[createCommentparentId="${parentId}"]`).show();
                $(`[createCommentparentId="${parentId}"] > textarea`).val("");

                $('#content').animate({
                    scrollTop: $(`[createCommentparentId="${parentId}"] > textarea`).offset().top
                }, scrollAnimationSpeed)
                    .promise()
                    .done(() => { $(`[createCommentparentId="${parentId}"] > textarea`).focus(); });
            })
            $(".abortCreateCommentCmd").off();
            $(".abortCreateCommentCmd").click(function (event) {
                event.preventDefault();
                commentsSection.restart();
                let parentId = $(this).attr("parentId");
                $(`[createCommentparentId="${parentId}"]`).hide();
            })

            $(".createCommentCmd").off();
            $(".createCommentCmd").click(function (event) {
                event.preventDefault();
                let parentId = $(this).attr("parentId");
                let commentText = $(this).parent().parent().find("textarea").val();
                commentsSection.postCommand("/Photos/CreateComment", { parentId, commentText });
                commentsSection.restart();
            })
            $(".CreateResponseCommentCmd").off();
            $(".CreateResponseCommentCmd").click(function () {
                commentsSection.pause();
                let parentId = $(this).attr("parentId");
                console.log($(`[createResponseparentId="${parentId}"]`)[0])
                $(`[createResponseparentId="${parentId}"]`).show();
                $(`[createResponseparentId="${parentId}"] > textarea`).val("");
                $('#content').animate({
                    scrollTop: $(`[createResponseparentId="${parentId}"] > textarea`).offset().top
                }, scrollAnimationSpeed)
                    .promise()
                    .done(() => { $(`[createResponseparentId="${parentId}"] > textarea`).focus(); });

            })
            $(".abortCreateResponseCmd").off();
            $(".abortCreateResponseCmd").click(function (event) {
                event.preventDefault();
                commentsSection.restart();
                let parentId = $(this).attr("parentId");
                $(`[createResponseparentId="${parentId}"]`).hide();
            })

            $(".createResponseCmd").off();
            $(".createResponseCmd").click(function (event) {
                event.preventDefault();
                let parentId = $(this).attr("parentId");
                let commentText = $(this).parent().parent().find("textarea").val();
                commentsSection.postCommand("/Photos/CreateComment", { parentId, commentText });
                commentsSection.restart();
            })
            $(".editCommentCmd").off();
            $(".editCommentCmd").click(function () {
                commentsSection.pause();
                let id = $(this).attr("commentId");
                $("#" + id).show();
                $("#" + id + "> textarea").focus();
                $("[commentId=" + id + "]").hide();
            })

            $(".abortEditCommentCmd").off();
            $(".abortEditCommentCmd").click(function (event) {
                event.preventDefault();
                commentsSection.restart();
                let id = $(this).attr("cmdCommentId");
                $("#" + id).hide();
                $("[commentId=" + id + "]").show();
            })

            $(".updateCommentCmd").off();
            $(".updateCommentCmd").click(function (event) {
                event.preventDefault();
                let commentId = $(this).attr("cmdCommentId");
                let commentText = $(this).parent().parent().find("textarea").val();
                commentsSection.postCommand("/Photos/UpdateComment", { commentId, commentText });
                commentsSection.restart();
            })

            $(".deleteCommentCmd").off()
            $(".deleteCommentCmd").click(function (event) {
                event.preventDefault();
                commentsSection.pause();
                let commentId = $(this).attr("cmdCommentId");
                commentsSection.confirmedCommand("Effacer?", `/Photos/DeleteComment?id=${commentId}`);
                commentsSection.restart();
            })
        }
    </script>
}

Views/Photos/Edit.cshtml
@{
    ViewBag.Title = "Modification de photo";
    Html.RenderPartial("PhotoForm");
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photos/GetDetails.cshtml
@model PhotosManager.Models.Photo
@{
    var user = ((PhotosManager.Models.User)Session["ConnectedUser"]);

    bool userLike = PhotosManager.Models.DB.Likes.ToList().Exists(l => (l.PhotoId == Model.Id && l.UserId == user.Id));
    bool userComment = PhotosManager.Models.DB.Comments.ToList().Exists(l => (l.PhotoId == Model.Id && l.OwnerId == user.Id));

    string photoLikedByConnectedUser = userLike ? "fa" : "fa-regular";
    string photoCommentByConnectedUser = userComment ? "fa-solid" : "fa-regular";

}

<div id="PhotoDetails">
    <div class="photoDetailsOwner">
        <div class="UserSmallAvatar" style="background-image:url('@Model.Owner.Avatar')" title="@Model.Owner.Name"></div>
        @Model.Owner.Name
    </div>
    <hr>
    <div class="photoDetailsTitle">@Model.Title</div>
    <a href="@Model.Image" target="_blank">
        <img src="@Model.Image" class="photoDetailsLargeImage">
    </a>
    <div class="photoDetailsCreationDate">
        @Helper.When(Model.CreationDate, true)
        <div class="likesSummary">
            @Model.Comments.Count()
            <i class=" cmdIconSmall @photoCommentByConnectedUser fa-comment" title="@Model.UsersCommentList"></i>

            @Model.Likes.Count()
            <div style="font-size:1.1em"
                 class="cmdIconSmall @photoLikedByConnectedUser fa-thumbs-up"
                 id="addRemoveLikeCmd"
                 photoId="@Model.Id"
                 title="@Html.Raw(Model.UsersLikesList)">
            </div>
        </div>

    </div>
    <div class="photoDetailsDescription">@Model.Description</div>
</div>

Views/Photos/GetPhotos.cshtml
@model IEnumerable<PhotosManager.Models.Photo>
@{
    var connectedUser = (PhotosManager.Models.User)Session["ConnectedUser"];
    bool showSearch = Session["PhotosShowSearch"] != null && (bool)Session["PhotosShowSearch"];

}

@foreach (var photo in Model)
{
    if (connectedUser.IsAdmin || photo.Shared || photo.OwnerId == connectedUser.Id)
    {
        bool userLike = PhotosManager.Models.DB.Likes.ToList().Exists(l => (l.PhotoId == photo.Id && l.UserId == connectedUser.Id));
        bool userComment = PhotosManager.Models.DB.Comments.ToList().Exists(l => (l.PhotoId == photo.Id && l.OwnerId == connectedUser.Id));

        string photoLikedByConnectedUser = userLike ? "fa" : "fa-regular";
        string photoCommentByConnectedUser = userComment ? "fa-solid" : "fa-regular";

        bool writeAccess = connectedUser.IsAdmin || photo.OwnerId == connectedUser.Id;
        <div class="photoLayout">
            <div class="photoTitleContainer" title="@photo.Description">
                <div class="photoTitle ellipsis">@photo.Title</div>
            </div>
            <a href="/Photos/Details/@photo.Id" title="Afficher les détails de @photo.Title" class="photDetailsLink">
                <div class="photoImage" style="background-image:url('@photo.Image')">
                    <div class="UserSmallAvatar transparentBackground" style="background-image: url('@photo.Owner.Avatar')" title="@photo.Owner.Name"></div>
                    @if (writeAccess && photo.Shared)
                    {
                        <div class="UserSmallAvatar transparentBackground" style="background-image:url('/Content/UI-Images/shared.png')" title="partagée"></div>
                    }
                </div>
                <div class="photoCreationDate">
                    @Helper.When(photo.CreationDate)

                    <div class="likesSummary">
                        @photo.Comments.Count()
                        <i class=" cmdIconSmall @photoCommentByConnectedUser fa-comment" title="@photo.UsersCommentList"></i>
                        @photo.LikesCount
                        <i class="cmdIconSmall @photoLikedByConnectedUser fa-thumbs-up" title="@photo.UsersLikesList" photoid="@photo.Id"></i>
                    </div>
                </div>
            </a>
        </div>
    }
}

Views/Photos/List.cshtml
@{
    ViewBag.Title = "Liste des photos";
    bool showSearch = Session["PhotosShowSearch"] != null && (bool)Session["PhotosShowSearch"];

}

<div id="PhotosPanel" class='photosLayout'> <!-- Auto refreshed panel --></div>

@section Scripts {
    <script>

        $(() => {
            let PhotosPanel = new AutoRefreshedPanel("PhotosPanel", "/Photos/GetPhotos", GPRR, attachEvent);

            var timeout = null;
            $('#searchToken').keyup(function () {
                clearTimeout(timeout);
                timeout = setTimeout(() => {
                    PhotosPanel.command("/Photos/SetSearchKeywords?keywords=" + $(this).val());
                }, 1000);
            });

            function attachEvent() {
                $("#PhotosPanel .fa-thumbs-up").click(function (e) {
                    PhotosPanel.command("/Photos/TogglePhotoLike/" + $(this).attr("photoId"));
                    e.preventDefault();
                });
            }
            $('#searchToken').change(function () {
                PhotosPanel.command("/Photos/SetSearchKeywords?keywords=" + $(this).val());
            });
            $('#searchToken').on("search", function () {
                PhotosPanel.command("/Photos/SetSearchKeywords?keywords=" + $(this).val());
            });
            // ascending sort of select option values
            /*$("#SelectedUser").html($("#SelectedUser option").sort(function (a, b) {
                return a.text == b.text ? 0 : a.text > b.text ? 1 : -1
            }))*/
            $('#SelectedUser').change(function () {
                PhotosPanel.command("/Photos/SetPhotoOwnerSearchId?id=" + $(this).val());
            })

            $("#SelectedUser option").each(function () {
                //$(this).text($(this).text().slice($(this).text().indexOf("-")+2));
            });
        })
    </script>
}

Views/Photos/RenderComments.cshtml
@model IEnumerable<PhotosManager.Models.Comment>
@{
    var user = ((PhotosManager.Models.User)Session["ConnectedUser"]);
    int currentPhotoId = (int)Session["currentPhotoId"];
    int currentCommentId = 0;
}
<div class="commentsLayout">
    @if (Model.Count() > 0)
    {
        foreach (var comment in Model)
        {
            currentCommentId = comment.Id;
            bool userLike = PhotosManager.Models.DB.Likes.ToList().Exists(l => (l.CommentId == comment.Id && l.UserId == user.Id));
            string commentLikedByConnectedUser = userLike ? "fa" : "fa-regular";

            <!-- Comment rendering -->
            <div class="commentLayout" commentId="@comment.Id">

                <div class="UserSmallAvatar" style="background-image:url('@comment.Owner.Avatar')" title="@comment.Owner.Name"></div>
                <div class="textComment">@Helper.ParseContent(comment.Text)</div>

                <div><!--spacer--></div>
                <div class="commentFooter">
                    @Helper.When(comment.CreationDate)
                    <div class="commentSubFooter">
                        @comment.Likes.Count()
                        <i class="cmdIconSmall @commentLikedByConnectedUser fa-thumbs-up" title="@comment.UsersLikesList" commentId="@comment.Id"></i>
                        <!-- Only owner can edit this comment -->
                        @if (comment.Owner.Id == user.Id)
                        {
                            <!-- Edit comment command icon -->
                            <i class="editCommentCmd cmdIconSmall fa fa-edit" commentId="@comment.Id"></i>
                        }
                        <!-- Create response command icon -->
                        <i class="CreateResponseCommentCmd cmdIconSmall fa-regular fa-comment" parentId="@comment.Id" title="Répondre/commenter"></i>
                    </div>
                </div>

            </div>

            <!-- Only owner can edit this comment -->
            if (comment.Owner.Id == user.Id)
            {
                <!-- Hidden programmatically edit comment UI -->
                <div class="editCommentLayout" id="@comment.Id" userId="@user.Id" ownerId="@comment.Owner.Id">

                    <div class="UserSmallAvatar" style="background-image:url('@comment.Owner.Avatar')" title="@comment.Owner.Name"></div>
                    <textarea class="form-control" rows="1" placeholder="répondre">@comment.Text</textarea>

                    <div><!--spacer--></div>
                    <div class="editCommentFooter">
                        <div></div>
                        <!-- Commit update command icon -->
                        <span class="updateCommentCmd cmdIconSmall fa fa-check" cmdCommentId="@comment.Id"></span>
                        <!-- Abort update command icon -->
                        <span class="abortEditCommentCmd cmdIconSmall fa fa-times" cmdCommentId="@comment.Id"></span>
                        <!-- Delete command icon -->
                        <span class="deleteCommentCmd cmdIconSmall fa fa-trash" cmdCommentId="@comment.Id"></span>
                    </div>

                </div>
            }

            <!-- Render comment responses (recursive)-->
            Html.RenderAction("Comments", "Photos", new { photoId = comment.PhotoId, parentId = comment.Id });

            <!-- Hidden programmatically create response comment UI -->
            <div class="responseLayout" photoId="@currentPhotoId" createResponseparentId="@currentCommentId">

                <div class="UserSmallAvatar" style="background-image:url('@user.Avatar')" title="@user.Name"></div>
                <textarea class="form-control" rows="1" placeholder="répondre"></textarea>

                <div><!--spacer--></div>
                <div class="editCommentFooter">
                    <div><!--spacer--></div>
                    <!-- Commit create command icon -->
                    <span class="createResponseCmd cmdIconSmall fa fa-check" parentId="@currentCommentId"></span>
                    <!-- Abort update command icon -->
                    <span class="abortCreateResponseCmd fa fa-times" parentId="@currentCommentId"></span>
                </div>

            </div>
        }
    }
</div>